# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My Courses' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My Courses
pod 'Alamofire', '~> 4.3'
pod 'SDWebImage/WebP', '~>3.8'
pod 'SideMenuController'
pod 'FSPagerView'
pod 'DropDown'
pod 'SwiftyJSON'
pod 'GoogleMaps'
pod 'Parchment'

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

pod 'GoogleSignIn'

pod 'TwitterKit'

end
